server:
  port : 9090
  
# the logging configuration is here
logging:
  level:
    root: INFO
    com.akg: DEBUG

common:
  number-of-executions: 50000
  notificator-url: http://localhost:8090/shutdown